### ISSUE TITLE
Remember what's been replied to

### ISSUE THREAD

**Issue by wjt** [wjt/fewerror#1]
Every time someone @fewerror follows retweets a tweet it's already replied to, it crashes:

```
[2013-11-27 21:01:08.549890 @markrendle] I just read all of @fewerror's tweets and it hasn't been right once yet. Satire, bug, or author less clever than they think they are?
--> @markrendle I think you mean “fewer clever”.
Traceback (most recent call last):
  File "fewerror.py", line 156, in <module>
    stream.userstream()
  File "/home/wjt/src/fewerror/env/local/lib/python2.7/site-packages/tweepy/streaming.py", line 193, in userstream
    self._start(async)
  File "/home/wjt/src/fewerror/env/local/lib/python2.7/site-packages/tweepy/streaming.py", line 181, in _start
    self._run()
  File "/home/wjt/src/fewerror/env/local/lib/python2.7/site-packages/tweepy/streaming.py", line 127, in _run
    self._read_loop(resp)
  File "/home/wjt/src/fewerror/env/local/lib/python2.7/site-packages/tweepy/streaming.py", line 171, in _read_loop
    self._data(next_status_obj)
  File "/home/wjt/src/fewerror/env/local/lib/python2.7/site-packages/tweepy/streaming.py", line 148, in _data
    if self.listener.on_data(data) is False:
  File "fewerror.py", line 93, in on_data
    super(LessListener, self).on_data(data)
  File "/home/wjt/src/fewerror/env/local/lib/python2.7/site-packages/tweepy/streaming.py", line 43, in on_data
    if self.on_status(status) is False:
  File "fewerror.py", line 117, in on_status
    r = self.api.update_status(reply, in_reply_to_status_id=status.id)
  File "/home/wjt/src/fewerror/env/local/lib/python2.7/site-packages/tweepy/binder.py", line 197, in _call
    return method.execute()
  File "/home/wjt/src/fewerror/env/local/lib/python2.7/site-packages/tweepy/binder.py", line 173, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: [{u'message': u'Status is a duplicate.', u'code': 187}]
```

I hadn't considered that it'd see tweets more than once. I'm glad it's being stopped from actually repeatedly replying by Twitter. It would be more auspicious to remember what's been replied to, though.

**Comment by wjt** [comment]
I fixed this literally years ago.
